/* ==========================================================================
   العربية التفاعلية — All Learning Content (BAB 3)
   Single source of truth. Pages read from here, never hardcode content.
   ========================================================================== */

const DATA = {

  chapters: [
    { number: 1, numeral_ar: '١', title_ar: 'الرِّيَاضَة', title_id: 'Olahraga',
      summary: 'Kosakata & dialog seputar aktivitas olahraga', status: 'soon', progress: 0 },
    { number: 2, numeral_ar: '٢', title_ar: 'أَصْحَابُ الْمِهْنَة', title_id: 'Para Pekerja Profesi',
      summary: 'Nama-nama profesi dan tugas sehari-hari', status: 'soon', progress: 0 },
    { number: 3, numeral_ar: '٣', title_ar: 'عِيَادَةُ الْمَرِيضِ', title_id: 'Menjenguk Orang Sakit',
      summary: 'Dialog, kosakata, qawaid & doa untuk yang sakit', status: 'available', progress: 0 },
  ],

  chapter3: {
    number: 3, numeral_ar: '٣',
    title_ar: 'عِيَادَةُ الْمَرِيضِ', title_id: 'Menjenguk Orang Sakit',
    description: "Belajar percakapan, kosakata, dan doa pendek saat menjenguk yang sakit, serta tata bahasa fi'il mādhī, fi'il mudhāri', dan jumlah fi'liyyah.",
    objectives: [
      'Mengenali kosakata penyakit, gejala, dan kegiatan menjenguk orang sakit',
      'Memahami struktur dialog: menanyakan keadaan, keluhan, dan mendoakan kesembuhan',
      'Mempraktikkan ungkapan مَاذَا بِكَ؟ / مِمَّ تَشْكُو؟ / شَفَاكَ اللَّهُ',
      "Membedakan fi'il mādhī dan fi'il mudhāri' beserta perubahannya sesuai pelaku",
      "Menyusun jumlah fi'liyyah sederhana (fi'il + fā'il + maf'ūl) bertema kesehatan",
    ],
  },

  hiwar: {
    scenes: [
      { id: 'scene-salam', label: 'Salam & Sapaan', label_ar: 'السَّلَامُ وَالتَّحِيَّة',
        illustration_ref: 'assets/images/hiwar/scene-salam.png',
        lines: [
          { speaker: 'أ', side: 'left',  ar: 'السَّلَامُ عَلَيْكُمْ يَا أَحْمَدُ', id: "Assalamu'alaikum, wahai Ahmad",
            audio_ref: null, audio_text: 'السَّلَامُ عَلَيْكُمْ يَا أَحْمَدُ' },
          { speaker: 'ب', side: 'right', ar: 'وَعَلَيْكُمُ السَّلَامُ وَرَحْمَةُ اللَّهِ، أَهْلًا وَسَهْلًا', id: "Wa'alaikumussalam warahmatullah, selamat datang",
            audio_ref: null, audio_text: 'وَعَلَيْكُمُ السَّلَامُ وَرَحْمَةُ اللَّهِ، أَهْلًا وَسَهْلًا' },
        ] },
      { id: 'scene-tanya', label: 'Menanyakan Kabar', label_ar: 'السُّؤَالُ عَنِ الْحَال',
        illustration_ref: 'assets/images/hiwar/scene-tanya.png',
        lines: [
          { speaker: 'أ', side: 'left',  ar: 'كَيْفَ حَالُكَ الْيَوْمَ يَا صَدِيقِي؟', id: 'Bagaimana keadaanmu hari ini, sahabatku?',
            audio_ref: null, audio_text: 'كَيْفَ حَالُكَ الْيَوْمَ يَا صَدِيقِي' },
          { speaker: 'ب', side: 'right', ar: 'أَنَا مَرِيضٌ قَلِيلًا، عِنْدِي حُمَّى وَصُدَاعٌ', id: 'Aku agak sakit, aku demam dan pusing',
            audio_ref: null, audio_text: 'أَنَا مَرِيضٌ قَلِيلًا، عِنْدِي حُمَّى وَصُدَاعٌ' },
        ] },
      { id: 'scene-syakwa', label: 'Menanyakan Keluhan', label_ar: 'السُّؤَالُ عَنِ الشَّكْوَى',
        illustration_ref: 'assets/images/hiwar/scene-syakwa.png',
        lines: [
          { speaker: 'أ', side: 'left',  ar: 'مِمَّ تَشْكُو؟ مَتَى شَعَرْتَ بِهَذَا الْأَلَمِ؟', id: 'Apa keluhanmu? Kapan kamu merasakan sakit ini?',
            audio_ref: null, audio_text: 'مِمَّ تَشْكُو؟ مَتَى شَعَرْتَ بِهَذَا الْأَلَمِ' },
          { speaker: 'ب', side: 'right', ar: 'شَعَرْتُ بِالْأَلَمِ مُنْذُ يَوْمَيْنِ، عِنْدِي أَلَمٌ فِي الرَّأْسِ', id: 'Aku merasakannya sejak dua hari lalu, kepalaku sakit',
            audio_ref: null, audio_text: 'شَعَرْتُ بِالْأَلَمِ مُنْذُ يَوْمَيْنِ، عِنْدِي أَلَمٌ فِي الرَّأْسِ' },
        ] },
      { id: 'scene-tabib', label: 'Soal ke Dokter', label_ar: 'زِيَارَةُ الطَّبِيب',
        illustration_ref: 'assets/images/hiwar/scene-tabib.png',
        lines: [
          { speaker: 'أ', side: 'left',  ar: 'هَلْ ذَهَبْتَ إِلَى الطَّبِيبِ؟', id: 'Apakah kamu sudah ke dokter?',
            audio_ref: null, audio_text: 'هَلْ ذَهَبْتَ إِلَى الطَّبِيبِ' },
          { speaker: 'ب', side: 'right', ar: 'نَعَمْ، ذَهَبْتُ أَمْسِ وَأَخَذْتُ الدَّوَاءَ مِنَ الصَّيْدَلِيَّةِ', id: 'Ya, aku ke sana kemarin dan mengambil obat dari apotek',
            audio_ref: null, audio_text: 'نَعَمْ، ذَهَبْتُ أَمْسِ وَأَخَذْتُ الدَّوَاءَ مِنَ الصَّيْدَلِيَّةِ' },
        ] },
      { id: 'scene-doa', label: 'Mendoakan Sembuh', label_ar: 'الدُّعَاءُ بِالشِّفَاء',
        illustration_ref: 'assets/images/hiwar/scene-doa.png',
        lines: [
          { speaker: 'أ', side: 'left',  ar: 'لَا بَأْسَ عَلَيْكَ، شَفَاكَ اللَّهُ شِفَاءً عَاجِلًا', id: 'Tidak apa-apa, semoga Allah menyembuhkanmu dengan segera',
            audio_ref: null, audio_text: 'لَا بَأْسَ عَلَيْكَ، شَفَاكَ اللَّهُ شِفَاءً عَاجِلًا' },
          { speaker: 'ب', side: 'right', ar: 'آمِينَ، شُكْرًا جَزِيلًا عَلَى زِيَارَتِكَ', id: 'Amin, terima kasih banyak atas kunjunganmu',
            audio_ref: null, audio_text: 'آمِينَ، شُكْرًا جَزِيلًا عَلَى زِيَارَتِكَ' },
        ] },
      { id: 'scene-wada', label: 'Pamit', label_ar: 'الْوَدَاع',
        illustration_ref: 'assets/images/hiwar/scene-wada.png',
        lines: [
          { speaker: 'أ', side: 'left',  ar: 'عَلَيْكَ بِالرَّاحَةِ، إِلَى اللِّقَاءِ فِي الْمَدْرَسَةِ', id: 'Istirahatlah, sampai jumpa di sekolah',
            audio_ref: null, audio_text: 'عَلَيْكَ بِالرَّاحَةِ، إِلَى اللِّقَاءِ فِي الْمَدْرَسَةِ' },
          { speaker: 'ب', side: 'right', ar: 'إِلَى اللِّقَاءِ، مَعَ السَّلَامَةِ', id: 'Sampai jumpa, hati-hati',
            audio_ref: null, audio_text: 'إِلَى اللِّقَاءِ، مَعَ السَّلَامَةِ' },
        ] },
    ],
    full_audio_ref: null,
    vocab: [
      { ar: 'كَيْفَ حَالُكَ',        id: 'Bagaimana keadaanmu' },
      { ar: 'مِمَّ تَشْكُو؟',         id: 'Apa keluhanmu?' },
      { ar: 'عِنْدِي…',              id: 'Aku menderita…' },
      { ar: 'لَا بَأْسَ عَلَيْكَ',    id: 'Jangan khawatir / tidak apa-apa' },
      { ar: 'شَفَاكَ اللَّهُ',         id: 'Semoga Allah menyembuhkanmu' },
    ],
  },

  mufrodat: [
    { ar: 'الطَّبِيب', transliteration: 'aṭ-Ṭabīb', meaning_id: 'Dokter',
      image_ref: 'assets/images/mufrodat/at-tabib.svg', audio_ref: null, audio_text: 'الطَّبِيب',
      example_ar: 'فَحَصَ الطَّبِيبُ الْمَرِيضَ', example_id: 'Dokter memeriksa si sakit' },
    { ar: 'الْمَرِيض', transliteration: 'al-Marīḍ', meaning_id: 'Orang sakit',
      image_ref: 'assets/images/mufrodat/al-marid.svg', audio_ref: null, audio_text: 'الْمَرِيض',
      example_ar: 'الْمَرِيضُ فِي الْغُرْفَةِ', example_id: 'Si sakit ada di kamar' },
    { ar: 'الْمُسْتَشْفَى', transliteration: 'al-Mustasyfā', meaning_id: 'Rumah sakit',
      image_ref: 'assets/images/mufrodat/al-mustashfa.svg', audio_ref: null, audio_text: 'الْمُسْتَشْفَى',
      example_ar: 'ذَهَبَ أَحْمَدُ إِلَى الْمُسْتَشْفَى', example_id: 'Ahmad pergi ke rumah sakit' },
    { ar: 'الصَّيْدَلِيَّة', transliteration: 'aṣ-Ṣaydaliyyah', meaning_id: 'Apotek',
      image_ref: 'assets/images/mufrodat/as-saydaliyyah.svg', audio_ref: null, audio_text: 'الصَّيْدَلِيَّة',
      example_ar: 'أَخَذْتُ الدَّوَاءَ مِنَ الصَّيْدَلِيَّةِ', example_id: 'Aku ambil obat dari apotek' },
    { ar: 'الدَّوَاء', transliteration: "ad-Dawā'", meaning_id: 'Obat',
      image_ref: 'assets/images/mufrodat/ad-dawa.svg', audio_ref: null, audio_text: 'الدَّوَاء',
      example_ar: 'تَنَاوَلَ الدَّوَاءَ بَعْدَ الْأَكْلِ', example_id: 'Ia minum obat setelah makan' },
    { ar: 'الْوَصْفَة الطِّبِّيَّة', transliteration: 'al-Waṣfah aṭ-Ṭibbiyyah', meaning_id: 'Resep dokter',
      image_ref: 'assets/images/mufrodat/al-wasfah.svg', audio_ref: null, audio_text: 'الْوَصْفَة الطِّبِّيَّة',
      example_ar: 'كَتَبَ الطَّبِيبُ الْوَصْفَةَ', example_id: 'Dokter menulis resep' },
    { ar: 'حُمَّى', transliteration: 'Ḥummā', meaning_id: 'Demam',
      image_ref: 'assets/images/mufrodat/humma.svg', audio_ref: null, audio_text: 'حُمَّى',
      example_ar: 'عِنْدِي حُمَّى شَدِيدَةٌ', example_id: 'Aku demam tinggi' },
    { ar: 'صُدَاع', transliteration: "Ṣudā'", meaning_id: 'Sakit kepala / pusing',
      image_ref: 'assets/images/mufrodat/sudaa.svg', audio_ref: null, audio_text: 'صُدَاع',
      example_ar: 'عِنْدِي صُدَاعٌ فِي الرَّأْسِ', example_id: 'Kepalaku pusing' },
    { ar: 'سُعَال', transliteration: "Su'āl", meaning_id: 'Batuk',
      image_ref: 'assets/images/mufrodat/sual.svg', audio_ref: null, audio_text: 'سُعَال',
      example_ar: 'عِنْدِي سُعَالٌ مُنْذُ يَوْمَيْنِ', example_id: 'Aku batuk sejak dua hari' },
    { ar: 'زُكَام', transliteration: 'Zukām', meaning_id: 'Flu / pilek',
      image_ref: 'assets/images/mufrodat/zukam.svg', audio_ref: null, audio_text: 'زُكَام',
      example_ar: 'أَنَا مُصَابٌ بِالزُّكَامِ', example_id: 'Aku terkena flu' },
    { ar: 'إِسْهَال', transliteration: 'Isyhāl', meaning_id: 'Diare',
      image_ref: 'assets/images/mufrodat/ishal.svg', audio_ref: null, audio_text: 'إِسْهَال',
      example_ar: 'عِنْدِي إِسْهَالٌ', example_id: 'Aku diare' },
    { ar: 'أَلَم', transliteration: 'Alam', meaning_id: 'Rasa sakit / nyeri',
      image_ref: 'assets/images/mufrodat/alam.svg', audio_ref: null, audio_text: 'أَلَم',
      example_ar: 'عِنْدِي أَلَمٌ فِي الْمَعِدَةِ', example_id: 'Perutku nyeri' },
  ],

  mufrodat_extra: [
    { ar: 'وَجَعُ الْأَسْنَان', id: 'Sakit gigi' },
    { ar: 'اِلْتِهَابُ الْحَلْق', id: 'Radang tenggorokan' },
    { ar: 'مَغَص', id: 'Sakit perut / mulas' },
    { ar: 'جُرْح', id: 'Luka' },
    { ar: 'دُوَارُ الرَّأْس', id: 'Pusing berputar' },
    { ar: 'حُقْنَة / إِبْرَة', id: 'Suntik / jarum suntik' },
    { ar: 'مِيزَانُ الْحَرَارَة', id: 'Termometer' },
  ],

  qawaid: {
    intro: {
      title_ar: 'التَّرْكِيب', title_id: 'Tata Bahasa',
      hook: 'Bayangkan kata kerja seperti MESIN WAKTU: kata yang sama bisa "berpindah waktu" — ذَهَبَ (sudah pergi) ↔ يَذْهَبُ (sedang/akan pergi). Ekornya juga berubah mengikuti pelaku.',
      summary: "Kata kerja (fi'il) berubah sesuai WAKTU (sudah/sedang) dan PELAKU. Kita pelajari fi'il mādhī, fi'il mudhāri', lalu merangkainya jadi jumlah fi'liyyah.",
    },
    topics: [
      {
        id: 'fiil-madhi',
        title_ar: 'الفِعْلُ الْمَاضِي', title_id: "Fi'il Mādhī (Kata Kerja Lampau)",
        icon: 'history',
        explanation: "Fi'il mādhī adalah kata kerja yang menunjukkan pekerjaan SUDAH terjadi (lampau). Cirinya: huruf akhir asalnya berharakat fathah, lalu diberi AKHIRAN sesuai pelaku.",
        key_points: [
          'Hafalan akhiran: ـْتُ (أنا), ـْتَ (أنتَ), ـْتِ (أنتِ), ـَتْ (هي), ـْنَا (نحن), ـُوا (هم)',
          'هُوَ memakai bentuk asli tanpa tambahan huruf',
        ],
        conjugation: {
          root_verb: 'ذَهَبَ', root_meaning: 'pergi', suffix_color: '#F5C84B',
          rows: [
            { pronoun_ar: 'هُوَ',  pronoun_id: 'Dia (lk)', verb_form: 'ذَهَبَ',  suffix: 'ـَ',   meaning: 'Dia (lk) telah pergi', audio_text: 'ذَهَبَ' },
            { pronoun_ar: 'هِيَ',  pronoun_id: 'Dia (pr)', verb_form: 'ذَهَبَتْ', suffix: 'ـَتْ', meaning: 'Dia (pr) telah pergi', audio_text: 'ذَهَبَتْ' },
            { pronoun_ar: 'أَنْتَ', pronoun_id: 'Kamu (lk)', verb_form: 'ذَهَبْتَ', suffix: 'ـْتَ', meaning: 'Kamu (lk) telah pergi', audio_text: 'ذَهَبْتَ' },
            { pronoun_ar: 'أَنْتِ', pronoun_id: 'Kamu (pr)', verb_form: 'ذَهَبْتِ', suffix: 'ـْتِ', meaning: 'Kamu (pr) telah pergi', audio_text: 'ذَهَبْتِ' },
            { pronoun_ar: 'أَنَا',  pronoun_id: 'Saya', verb_form: 'ذَهَبْتُ', suffix: 'ـْتُ', meaning: 'Saya telah pergi', audio_text: 'ذَهَبْتُ' },
            { pronoun_ar: 'نَحْنُ', pronoun_id: 'Kami', verb_form: 'ذَهَبْنَا', suffix: 'ـْنَا', meaning: 'Kami telah pergi', audio_text: 'ذَهَبْنَا' },
            { pronoun_ar: 'هُمْ',  pronoun_id: 'Mereka (lk)', verb_form: 'ذَهَبُوا', suffix: 'ـُوا', meaning: 'Mereka (lk) telah pergi', audio_text: 'ذَهَبُوا' },
          ],
        },
        examples: [
          { ar: 'ذَهَبْتُ إِلَى الطَّبِيبِ', id: 'Saya pergi ke dokter', highlight_word: 'ذَهَبْتُ', grammar_note: "Fi'il mādhī, pelaku: أَنَا" },
          { ar: 'أَخَذْتُ الدَّوَاءَ', id: 'Saya mengambil obat', highlight_word: 'أَخَذْتُ', grammar_note: "Fi'il mādhī, pelaku: أَنَا" },
          { ar: 'شَفَاكَ اللَّهُ', id: 'Semoga Allah menyembuhkanmu', highlight_word: 'شَفَاكَ', grammar_note: "Fi'il mādhī + dhamir كَ" },
        ],
        interactive: { type: 'conjugation_explorer' },
      },
      {
        id: 'fiil-mudhari',
        title_ar: 'الفِعْلُ الْمُضَارِع', title_id: "Fi'il Mudhāri' (Sekarang/Akan)",
        icon: 'play',
        explanation: "Fi'il mudhāri' menunjukkan pekerjaan yang SEDANG / AKAN terjadi atau kebiasaan. Cirinya: SELALU diawali huruf mudhāra'ah → أَنَيْتُ (أ، ن، ي، ت).",
        mudharaah: [
          { huruf: 'أ', for: 'أَنَا', example: 'أَذْهَبُ' },
          { huruf: 'ن', for: 'نَحْنُ', example: 'نَذْهَبُ' },
          { huruf: 'ي', for: 'هُوَ / هُمْ', example: 'يَذْهَبُ' },
          { huruf: 'ت', for: 'هِيَ / أَنْتَ / أَنْتِ', example: 'تَذْهَبُ' },
        ],
        verb_pairs: [
          { madhi: 'ذَهَبَ', mudhari: 'يَذْهَبُ', meaning: 'pergi' },
          { madhi: 'كَتَبَ', mudhari: 'يَكْتُبُ', meaning: 'menulis' },
          { madhi: 'شَرِبَ', mudhari: 'يَشْرَبُ', meaning: 'minum' },
          { madhi: 'فَحَصَ', mudhari: 'يَفْحَصُ', meaning: 'memeriksa' },
          { madhi: 'شَعَرَ', mudhari: 'يَشْعُرُ', meaning: 'merasa' },
          { madhi: 'سَأَلَ', mudhari: 'يَسْأَلُ', meaning: 'bertanya' },
          { madhi: 'جَلَسَ', mudhari: 'يَجْلِسُ', meaning: 'duduk' },
          { madhi: 'تَنَاوَلَ', mudhari: 'يَتَنَاوَلُ', meaning: 'mengonsumsi' },
        ],
        conjugation: {
          root_verb: 'يَذْهَبُ', root_meaning: 'pergi',
          rows: [
            { pronoun_ar: 'أَنَا',  pronoun_id: 'Saya', verb_form: 'أَذْهَبُ', meaning: 'Saya pergi', audio_text: 'أَذْهَبُ' },
            { pronoun_ar: 'نَحْنُ', pronoun_id: 'Kami', verb_form: 'نَذْهَبُ', meaning: 'Kami pergi', audio_text: 'نَذْهَبُ' },
            { pronoun_ar: 'هُوَ',  pronoun_id: 'Dia (lk)', verb_form: 'يَذْهَبُ', meaning: 'Dia (lk) pergi', audio_text: 'يَذْهَبُ' },
            { pronoun_ar: 'هِيَ',  pronoun_id: 'Dia (pr)', verb_form: 'تَذْهَبُ', meaning: 'Dia (pr) pergi', audio_text: 'تَذْهَبُ' },
            { pronoun_ar: 'أَنْتَ', pronoun_id: 'Kamu (lk)', verb_form: 'تَذْهَبُ', meaning: 'Kamu (lk) pergi', audio_text: 'تَذْهَبُ' },
            { pronoun_ar: 'أَنْتِ', pronoun_id: 'Kamu (pr)', verb_form: 'تَذْهَبِينَ', meaning: 'Kamu (pr) pergi', audio_text: 'تَذْهَبِينَ' },
            { pronoun_ar: 'هُمْ',  pronoun_id: 'Mereka (lk)', verb_form: 'يَذْهَبُونَ', meaning: 'Mereka (lk) pergi', audio_text: 'يَذْهَبُونَ' },
          ],
        },
        examples: [
          { ar: 'يَفْحَصُ الطَّبِيبُ الْمَرِيضَ', id: 'Dokter memeriksa si sakit', highlight_word: 'يَفْحَصُ', grammar_note: "Mudhāri', huruf ي" },
          { ar: 'أَشْرَبُ الدَّوَاءَ', id: 'Saya minum obat', highlight_word: 'أَشْرَبُ', grammar_note: "Mudhāri', huruf أ (أنا)" },
        ],
        interactive: { type: 'verb_transformer' },
      },
      {
        id: 'jumlah-filiyyah',
        title_ar: 'الْجُمْلَةُ الْفِعْلِيَّة', title_id: "Jumlah Fi'liyyah (Kalimat Verbal)",
        icon: 'layout',
        explanation: "Jumlah fi'liyyah adalah kalimat yang DIAWALI fi'il. Polanya: فِعْل + فَاعِل + (مَفْعُول بِهِ). Fā'il selalu marfū' (dhammah), maf'ūl manshūb (fathah).",
        rule_note: "Jika fā'il-nya perempuan (muannats) dan langsung setelah fi'il mādhī, fi'il diberi tambahan تْ (tā' ta'nīts). Contoh: عَالَجَ (lk) → فَحَصَتْ (pr).",
        structure: [
          { role_ar: 'فِعْل',         role_id: 'Kata kerja',        color: '#34A853' },
          { role_ar: 'فَاعِل',        role_id: 'Pelaku (dhammah)',   color: '#4285F4' },
          { role_ar: 'مَفْعُول بِهِ', role_id: 'Objek (fathah)',    color: '#F9A825' },
        ],
        examples: [
          { ar: 'ذَهَبَ أَحْمَدُ إِلَى الْمُسْتَشْفَى', id: 'Ahmad pergi ke rumah sakit',
            parts: [ { text: 'ذَهَبَ', role: 'fiil' }, { text: 'أَحْمَدُ', role: 'fail' }, { text: 'إِلَى الْمُسْتَشْفَى', role: 'jar' } ] },
          { ar: 'عَالَجَ الطَّبِيبُ الْمَرِيضَ', id: 'Dokter mengobati si sakit',
            parts: [ { text: 'عَالَجَ', role: 'fiil' }, { text: 'الطَّبِيبُ', role: 'fail' }, { text: 'الْمَرِيضَ', role: 'maful' } ] },
          { ar: 'فَحَصَتْ الطَّبِيبَةُ الْمَرِيضَةَ', id: 'Dokter (pr) memeriksa pasien (pr)',
            parts: [ { text: 'فَحَصَتْ', role: 'fiil' }, { text: 'الطَّبِيبَةُ', role: 'fail' }, { text: 'الْمَرِيضَةَ', role: 'maful' } ] },
          { ar: 'شَرِبَ الْوَلَدُ الدَّوَاءَ', id: 'Anak itu minum obat',
            parts: [ { text: 'شَرِبَ', role: 'fiil' }, { text: 'الْوَلَدُ', role: 'fail' }, { text: 'الدَّوَاءَ', role: 'maful' } ] },
          { ar: 'كَتَبَ الطَّبِيبُ الْوَصْفَةَ', id: 'Dokter menulis resep',
            parts: [ { text: 'كَتَبَ', role: 'fiil' }, { text: 'الطَّبِيبُ', role: 'fail' }, { text: 'الْوَصْفَةَ', role: 'maful' } ] },
        ],
        builder_sets: [
          { tokens: ['الْمَرِيضَ', 'عَالَجَ', 'الطَّبِيبُ'], answer: 'عَالَجَ الطَّبِيبُ الْمَرِيضَ' },
          { tokens: ['الدَّوَاءَ', 'شَرِبَ', 'الْوَلَدُ'], answer: 'شَرِبَ الْوَلَدُ الدَّوَاءَ' },
          { tokens: ['الْوَصْفَةَ', 'الطَّبِيبُ', 'كَتَبَ'], answer: 'كَتَبَ الطَّبِيبُ الْوَصْفَةَ' },
        ],
        interactive: { type: 'sentence_builder' },
      },
    ],
  },

  tadribat1: {
    scope: 'hiwar_mufrodat', xp_per_correct: 10, next_section: 'qawaid',
    questions: [
      { type: 'audio', prompt: 'Dengarkan, lalu pilih artinya.', audio_text: 'الطَّبِيب', arabic_display: null,
        options: ['Dokter', 'Perawat', 'Pasien', 'Apoteker'], correct_index: 0,
        explanation: 'الطَّبِيب (aṭ-Ṭabīb) artinya Dokter.' },
      { type: 'audio', prompt: 'Dengarkan ungkapan ini, apa maksudnya?', audio_text: 'عِنْدِي صُدَاعٌ', arabic_display: null,
        options: ['Aku lapar', 'Aku pusing/sakit kepala', 'Aku lelah', 'Aku sehat'], correct_index: 1,
        explanation: 'عِنْدِي صُدَاعٌ = Aku sakit kepala / pusing.' },
      { type: 'audio', prompt: 'Dengarkan doa ini, apa artinya?', audio_text: 'شَفَاكَ اللَّهُ', arabic_display: null,
        options: ['Semoga Allah menyembuhkanmu', 'Semoga Allah merahmatimu', 'Terima kasih', 'Selamat datang'], correct_index: 0,
        explanation: 'شَفَاكَ اللَّهُ = Semoga Allah menyembuhkanmu.' },
      { type: 'audio', prompt: 'Dengarkan pertanyaan ini. Jawaban yang tepat adalah…', audio_text: 'هَلْ ذَهَبْتَ إِلَى الطَّبِيبِ', arabic_display: null,
        options: ['نَعَمْ، ذَهَبْتُ أَمْسِ', 'أَنَا طَالِبٌ', 'فِي الْمَدْرَسَةِ', 'شُكْرًا'], correct_index: 0,
        explanation: '"Apakah kamu sudah ke dokter?" dijawab "Ya, aku ke sana kemarin".' },
      { type: 'audio', prompt: 'Dengarkan kata ini, apa artinya?', audio_text: 'الصَّيْدَلِيَّة', arabic_display: null,
        options: ['Sekolah', 'Masjid', 'Apotek', 'Pasar'], correct_index: 2,
        explanation: 'الصَّيْدَلِيَّة (aṣ-Ṣaydaliyyah) = Apotek.' },
      { type: 'text', prompt: 'Apa arti kata berikut?', audio_text: null, arabic_display: 'الْمَرِيض',
        options: ['Dokter', 'Orang sakit', 'Obat', 'Rumah sakit'], correct_index: 1,
        explanation: 'الْمَرِيض (al-Marīḍ) = Orang sakit.' },
      { type: 'text', prompt: 'Lengkapi jawaban salam: "…عَلَيْكُمُ السَّلَامُ"', audio_text: null, arabic_display: null,
        options: ['وَ', 'فَ', 'ثُمَّ', 'بَلْ'], correct_index: 0,
        explanation: 'Jawaban salam: وَعَلَيْكُمُ السَّلَامُ.' },
      { type: 'text', prompt: 'Dalam dialog, apa keluhan Ahmad?', audio_text: null, arabic_display: null,
        options: ['Sakit gigi', 'Demam dan pusing', 'Diare', 'Patah kaki'], correct_index: 1,
        explanation: 'Ahmad berkata: عِنْدِي حُمَّى وَصُدَاعٌ (demam dan pusing).' },
      { type: 'text', prompt: 'Apa arti "الدَّوَاء"?', audio_text: null, arabic_display: 'الدَّوَاء',
        options: ['Penyakit', 'Obat', 'Makanan', 'Air'], correct_index: 1,
        explanation: "الدَّوَاء (ad-Dawā') = Obat." },
      { type: 'text', prompt: 'Ungkapan mana yang berarti "Apa keluhanmu?"', audio_text: null, arabic_display: null,
        options: ['كَيْفَ حَالُكَ', 'مِمَّ تَشْكُو', 'مَا اسْمُكَ', 'أَيْنَ تَسْكُنُ'], correct_index: 1,
        explanation: 'مِمَّ تَشْكُو؟ = Apa keluhanmu?' },
    ],
  },

  tadribat2: {
    scope: 'qawaid', xp_per_correct: 10, next_section: 'chapter_overview',
    questions: [
      { type: 'mcq', prompt: "Bentuk fi'il mādhī dari ذَهَبَ untuk pelaku أَنَا?", arabic_display: null,
        options: ['ذَهَبَ', 'ذَهَبْتُ', 'ذَهَبَتْ', 'ذَهَبُوا'], correct_index: 1,
        explanation: 'أَنَا memakai akhiran ـْتُ → ذَهَبْتُ.' },
      { type: 'identify', prompt: "Siapa pelaku (fā'il) kalimat berikut?", arabic_display: 'ذَهَبَتْ إِلَى الْمُسْتَشْفَى',
        options: ['هُوَ', 'هِيَ', 'أَنَا', 'هُمْ'], correct_index: 1,
        explanation: "Akhiran ـَتْ (tā' ta'nīts) menandakan هِيَ (perempuan)." },
      { type: 'transform', prompt: "Ubah ke fi'il mudhāri': كَتَبَ → ?", arabic_display: 'كَتَبَ',
        options: ['يَكْتُبُ', 'كَتَبْتُ', 'تَكْتُبُ', 'اُكْتُبْ'], correct_index: 0,
        explanation: "كَتَبَ (mādhī) → يَكْتُبُ (mudhāri', هُوَ)." },
      { type: 'mcq', prompt: "Huruf mudhāra'ah untuk dhamir أَنَا adalah…", arabic_display: null,
        options: ['أ', 'ن', 'ي', 'ت'], correct_index: 0,
        explanation: "أَنَيْتُ: أَ untuk أَنَا → أَذْهَبُ." },
      { type: 'mcq', prompt: "Pola dasar jumlah fi'liyyah adalah…", arabic_display: null,
        options: ['فَاعِل + فِعْل', 'فِعْل + فَاعِل', 'اِسْم + خَبَر', 'حَرْف + اِسْم'], correct_index: 1,
        explanation: "Diawali fi'il lalu fā'il (+ maf'ūl): فِعْل + فَاعِل + مَفْعُول." },
      { type: 'mcq', prompt: 'Lengkapi: "… الطَّبِيبَةُ الْمَرِيضَ" (pelaku perempuan)', arabic_display: '… الطَّبِيبَةُ الْمَرِيضَ',
        options: ['فَحَصَ', 'فَحَصَتْ', 'يَفْحَصُ', 'اِفْحَصْ'], correct_index: 1,
        explanation: "Fā'il muannats → fi'il mādhī + تْ → فَحَصَتْ." },
      { type: 'mcq', prompt: "Bentuk fi'il mādhī أَخَذَ (mengambil) untuk هُمْ?", arabic_display: null,
        options: ['أَخَذَ', 'أَخَذَتْ', 'أَخَذْتُ', 'أَخَذُوا'], correct_index: 3,
        explanation: 'هُمْ memakai akhiran ـُوا → أَخَذُوا.' },
      { type: 'identify', prompt: 'Kata "شَفَاكَ" dalam kalimat berikut termasuk…', arabic_display: 'شَفَاكَ اللَّهُ',
        options: ['Isim (kata benda)', 'Harf (kata sambung)', "Fi'il mādhī", "Fi'il mudhāri'"], correct_index: 2,
        explanation: 'شَفَى = menyembuhkan (lampau); كَ adalah dhamir objek.' },
      { type: 'mcq', prompt: 'Lengkapi (cerita LKS): "… سَلْمَى إِلَى الْعِيَادَةِ"', arabic_display: '… سَلْمَى إِلَى عِيَادَةِ الطَّبِيبَةِ',
        options: ['وَصَلَ', 'وَصَلَتْ', 'يَصِلُ', 'صِلْ'], correct_index: 1,
        explanation: 'سَلْمَى perempuan → وَصَلَ menjadi وَصَلَتْ.' },
      { type: 'order', prompt: "Susun menjadi jumlah fi'liyyah yang benar.", arabic_display: null,
        tokens: ['عَالَجَ', 'الطَّبِيبُ', 'الْمَرِيضَ'], answer_order: 'عَالَجَ الطَّبِيبُ الْمَرِيضَ',
        options: ['عَالَجَ الطَّبِيبُ الْمَرِيضَ', 'الطَّبِيبُ عَالَجَ الْمَرِيضَ', 'الْمَرِيضَ عَالَجَ الطَّبِيبُ', 'عَالَجَ الْمَرِيضَ الطَّبِيبُ'],
        correct_index: 0,
        explanation: "Jumlah fi'liyyah: fi'il (عَالَجَ) → fā'il (الطَّبِيبُ) → maf'ūl (الْمَرِيضَ)." },
    ],
  },

  ui: {
    hero: {
      title_ar: 'العَرَبِيَّةُ التَّفَاعُلِيَّةُ',
      badge: 'Belajar Bahasa Arab · Interaktif',
      subtitle: 'Belajar bahasa Arab dengan cara yang seru dan mudah — dialog, kosakata, dan latihan interaktif.',
      subtitle_ar: 'تَعَلَّمْ العَرَبِيَّةَ بِسُهُولَةٍ وَمُتْعَةٍ',
      cta_primary: 'Mulai Belajar', cta_secondary: 'Lihat Materi',
    },
    features: [
      { icon: 'message', title: 'Dialog Interaktif',  desc: 'Dengarkan percakapan nyata dengan audio dan terjemahan' },
      { icon: 'layers',  title: 'Flashcard Kosakata', desc: 'Pelajari kosa kata baru dengan kartu balik yang menyenangkan' },
      { icon: 'edit',    title: 'Latihan & Ujian',    desc: 'Uji pemahamanmu dengan soal interaktif dan feedback langsung' },
    ],
    feedback: {
      correct: 'Mantap! Jawaban kamu benar 🎉',
      wrong: 'Belum tepat, coba pelajari lagi 💪',
      quiz_complete: 'Latihan Selesai!',
    },
    footer: 'العربية التفاعلية · SMA Islam Assyafiiyah 02 · Made for learning, with ❤️',
  },
};

window.DATA = DATA;
